### ISSUE TITLE
Apple link is broken

### ISSUE THREAD

**Issue by pbasista** [patjak/facetimehd-firmware#1]
The currently used link:

https://support.apple.com/downloads/DL1858/en_US/osxupd10.11.3.dmg

to OS X update at Apple's website no longer works.

**Comment by offlinehacker** [comment]
Seems like download link can be obtained here: https://support.apple.com/kb/DL1877?locale=en_US

**Comment by offlinehacker** [comment]
Managed to retrive new offsets, this command extracts new firmware:

`curl -s -L -r 204909802-207733123 https://updates.cdn-apple.com/2019/cert/041-88431-20191011-e7ee7d98-2878-4cd9-bc0a-d98b3a1e
24b1/OSXUpd10.11.5.dmg | xzcat | cpio --format odc -i -d "./System/Library/Extensions/AppleCameraInterface.kext/Contents/MacOS/AppleCameraInterface"`

**Comment by offlinehacker** [comment]
This was a command that helped me to find offsets: `binwalk -R "\xFD\x37\x7A\x58\x5A" -c OSXUpd10.11.5.dmg | tail -n +4 | cut -d " " -f 1 | xargs -I{} sh -c "echo stream offset {} >&2 && dd if=OSXUpd10.11.5.dmg skip={}  bs=1 | xzcat | cpio --format odc -t" | grep -i AppleCameraInterface`

**Comment by xmixahlx** [comment]
the download links are case sensitive, so you must use:
https://support.apple.com/downloads/DL1858/en_US/OSXUpd10.11.3.dmg
https://support.apple.com/downloads/DL1877/en_US/OSXUpd10.11.5.dmg

you must also use -k with curl to bypass the cert error.
