### ISSUE TITLE
Request: Licence & release

### ISSUE THREAD

**Issue by mulderje** [patjak/facetimehd-firmware#10]
I am working on [packaging spec files](https://github.com/mulderje/facetimehd-kmod-rpm) for this and facetimehd to ease building on fedora systems. Eventually I would like to get these up and building on rpmfusion or something similar, but for now just making it easier to get installed on my old macbook. Would it be possible to please add a license and to cut a tag/release here? 

Thanks!
jon

**Comment by patjak** [comment]
Hi, sorry for the delay. I rarely have time to dig through the issues here. I have tagged a release and uploaded a LICENSE file. Hopefully that should do it. But note that the license doesn't cover the downloaded firmware file itself.

**Comment by mulderje** [comment]
Thanks, and understood!
