### ISSUE TITLE
Install bug

### ISSUE THREAD

**Issue by JohnDeeBDD** [patjak/facetimehd-firmware#4]
I am following directions from [Ask Ubuntu](https://askubuntu.com/questions/990218/camera-not-working-on-macbook-pro)

Getting:
```
Makefile:34: recipe for target 'AppleCameraInterface' failed
make: *** [AppleCameraInterface] Error 1
```

**Comment by JohnDeeBDD** [comment]
I think it has something to do with this? 
https://github.com/patjak/bcwc_pcie/wiki/Get-Started#devvideo-not-created
maybe... i don't really know what i'm talking about! :)

**Comment by Picajoluna** [comment]
@JohnDeeBDD 
I'm getting the same bug -- I also don't have a /dev/video created, and also don't know much what I'm talking about... Any luck with this?

I came from this Medium article: https://medium.com/@racter/how-to-install-ubuntu-16-04-on-a-retina-macbook-11-2-74e7779c0e47

**Comment by JohnDeeBDD** [comment]
I got it to work. Not sure exactly what I did! I installed WordPress, then it worked. Some particular dependency. Try installing a LAMP stack then do it again.

**Comment by Picajoluna** [comment]
You're right, I was missing a dependency.
```
Checking dependencies for driver download...
/usr/bin/curl
/usr/bin/xzcat
which: no cpio in (/home/john/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin)
```

I fixed it by installing [cpio](https://www.archlinux.org/packages/extra/x86_64/cpio/): `sudo pacman -S cpio`.
